// Lesson content for the Learn section, organized by topic. Each lesson has a
// few content sections plus a short interactive quiz; LearnPage.jsx renders
// this data and useLessonProgress.js tracks which lessons a learner has
// passed (persisted to localStorage, mirroring the onboarding "seen" flag).

export const LEARN_TOPICS = [
  {
    id: 'getting-started',
    title: 'Getting Started',
    icon: '🚀',
    lessons: [
      {
        id: 'what-is-paper-trading',
        title: 'What is paper trading?',
        summary: 'What this simulator does — and doesn\'t do — with your money.',
        sections: [
          {
            heading: 'The short version',
            body: "Investment Trainer is a paper-trading simulator. That means every price you see is a real, market price (delayed by data provider rules), but every dollar you trade with is pretend. There's no bank account, brokerage, or card connected — the $10,000 you start with is virtual cash that only exists inside this app.",
          },
          {
            heading: 'Why practice with fake money?',
            body: "Real investing has real consequences: a bad trade can cost you rent money. Paper trading removes that risk so you can make mistakes, watch what happens, and build intuition for how markets move before any real money is on the line. Professional traders and finance students use this exact technique to test strategies.",
          },
          {
            heading: "What paper trading won't teach you",
            body: "Two things behave differently once real money is on the line: the emotional pressure of watching a real loss grow, and the cost of trading (fees, taxes, and the fact that large real orders can nudge the market price). Keep that in mind for later — the mechanics here are close, but the stakes and the psychology aren't.",
          },
        ],
        quiz: [
          {
            question: 'In Investment Trainer, where do the stock prices come from?',
            options: [
              'Randomly generated by the app',
              'Real market data, just like a live brokerage app',
              'Prices set by other players',
              'Historical prices from 10 years ago',
            ],
            correctIndex: 1,
            explanation: 'Prices are pulled from real market data — only the money you trade with is fake.',
          },
          {
            question: 'What is the main advantage of paper trading before investing real money?',
            options: [
              "It guarantees you'll make money later",
              'It removes financial risk while you learn how markets behave',
              'It is required by law before opening a brokerage account',
              'It automatically picks good stocks for you',
            ],
            correctIndex: 1,
            explanation: 'Paper trading lets you practice decision-making without risking real money.',
          },
        ],
      },
      {
        id: 'how-this-simulator-works',
        title: 'How this simulator works',
        summary: 'Starting cash, the trading loop, and what gets tracked for you.',
        sections: [
          {
            heading: 'Your starting point',
            body: 'Every new account starts with $10,000 in virtual cash. That number is a constant across all accounts, which is what makes the Leaderboard a fair comparison — everyone starts from the same line.',
          },
          {
            heading: 'The trading loop',
            list: [
              'Search for a company or ticker symbol on the Dashboard.',
              'Review its current price and recent price chart.',
              'Place a simulated buy or sell market order.',
              'Watch your holdings, cash, and profit/loss update immediately.',
              'Check the Leaderboard to see how your return compares to other traders.',
            ],
          },
          {
            heading: 'Everything is tracked for you',
            body: "Every order you place is saved to your transaction history, and your holdings automatically combine into an average cost when you buy the same stock more than once. You never have to do the math by hand — this Learn section is here to help you understand what the numbers mean.",
          },
        ],
        quiz: [
          {
            question: 'How much virtual cash does every new account start with?',
            options: ['$1,000', '$5,000', '$10,000', '$100,000'],
            correctIndex: 2,
            explanation: 'Every account starts with $10,000 in virtual cash — the same for everyone.',
          },
          {
            question: 'Why does every account start with the same amount of cash?',
            options: [
              "It's a technical limitation",
              'So the Leaderboard is a fair, apples-to-apples comparison',
              "It's the maximum allowed",
              'It has no particular reason',
            ],
            correctIndex: 1,
            explanation: 'A shared starting point means leaderboard rankings reflect trading decisions, not who started with more money.',
          },
        ],
      },
    ],
  },
  {
    id: 'reading-the-market',
    title: 'Reading the Market',
    icon: '📈',
    lessons: [
      {
        id: 'ticker-symbols-quotes',
        title: 'Ticker symbols & quotes',
        summary: 'How to read a stock symbol, price, and market state.',
        sections: [
          {
            heading: 'What a ticker symbol is',
            body: "A ticker symbol is the short code that identifies a company on a stock exchange — AAPL for Apple, TSLA for Tesla, MSFT for Microsoft. You'll use these symbols to search for and trade a company in the app.",
          },
          {
            heading: 'Reading a quote',
            body: 'When you look up a stock you\'ll see its current price, the dollar and percent change from the previous close, and a market state (PRE, REGULAR, POST, or CLOSED). The change tells the story of the day so far — a stock at $150, up $3 (+2%), has gained ground since the market opened.',
          },
          {
            heading: 'Market state matters',
            body: "Markets aren't open 24/7. REGULAR means the main trading session is live. PRE and POST are the shorter, less liquid windows before and after it. CLOSED means the price you're seeing is simply the last available price — it won't move until trading resumes.",
          },
        ],
        quiz: [
          {
            question: 'What does the ticker symbol AAPL represent?',
            options: ['A stock exchange', 'Apple Inc.', 'An order type', 'A type of mutual fund'],
            correctIndex: 1,
            explanation: "AAPL is Apple Inc.'s ticker symbol on the NASDAQ exchange.",
          },
          {
            question: 'If a quote shows a market state of CLOSED, what does that mean?',
            options: [
              'The company went bankrupt',
              "You can't ever buy that stock again",
              "The price shown is the last traded price and won't move until the market reopens",
              'The price is fake',
            ],
            correctIndex: 2,
            explanation: "CLOSED just means the exchange isn't currently trading that symbol — the price is frozen at its last trade.",
          },
        ],
      },
      {
        id: 'reading-a-price-chart',
        title: 'Reading a price chart',
        summary: 'What the axes mean, and why timeframe changes the story.',
        sections: [
          {
            heading: 'What the chart shows',
            body: "The price chart plots a stock's closing price over time. The horizontal axis is time, the vertical axis is price — an upward-sloping line means the price has been rising over that period, a downward slope means it's been falling.",
          },
          {
            heading: 'Choosing a timeframe',
            body: "Switching between 1D, 1W, 1M, and longer ranges changes the story the chart tells. A stock can be down for the day but up for the year — neither view is \"wrong\", they just answer different questions. Zooming out generally smooths over daily noise and shows the longer trend.",
          },
          {
            heading: 'A chart is not a prediction',
            body: "It's tempting to draw a line through the recent past and extend it into the future — but a price chart only shows what already happened. It's useful for spotting trends and volatility, not for guaranteeing what comes next.",
          },
        ],
        quiz: [
          {
            question: 'On a price chart, what does the vertical axis usually represent?',
            options: ['Time', 'Trading volume', 'Price', 'Number of investors'],
            correctIndex: 2,
            explanation: 'The vertical axis plots price; the horizontal axis plots time.',
          },
          {
            question: "Why might a stock look 'down' on a 1-day chart but 'up' on a 1-year chart?",
            options: [
              "That's impossible — charts always agree",
              'Different timeframes cover different periods and can tell different stories',
              'The 1-year chart is always wrong',
              'Prices reset every year',
            ],
            correctIndex: 1,
            explanation: 'Short-term dips are common even inside a longer uptrend (and vice versa) — timeframe changes the story.',
          },
        ],
      },
    ],
  },
  {
    id: 'placing-orders',
    title: 'Placing Orders',
    icon: '🧾',
    lessons: [
      {
        id: 'market-orders',
        title: 'Market orders',
        summary: 'What a market order does, and the trade-off it makes.',
        sections: [
          {
            heading: 'What a market order does',
            body: 'A market order tells the system: buy (or sell) this stock right now, at whatever the current price is. It\'s the simplest order type, and it\'s what every trade in this simulator uses.',
          },
          {
            heading: 'The trade-off',
            body: "Speed and certainty of execution come at a small cost: you don't get to name your price. In fast-moving real markets, the price you see and the price you actually pay can differ slightly by the time your order reaches the exchange. Real brokerages also offer \"limit orders\", which let you set a maximum buy price or minimum sell price — Investment Trainer only supports market orders to keep things simple.",
          },
          {
            heading: 'Before you click Buy',
            body: "Since a market order executes immediately, double-check the share count and estimated cost shown in the trade panel before confirming — there's no undo button once an order is placed, just like in a real brokerage.",
          },
        ],
        quiz: [
          {
            question: 'What does a market order guarantee?',
            options: ['A specific price', 'Immediate execution at the current price', 'A profit', "That the price won't change"],
            correctIndex: 1,
            explanation: 'A market order prioritizes speed of execution over price control — it fills right away at the going price.',
          },
          {
            question: 'What order type does Investment Trainer support?',
            options: ['Limit orders only', 'Stop orders only', 'Market orders only', 'Options contracts'],
            correctIndex: 2,
            explanation: 'To keep things simple, every trade in this simulator is a market order.',
          },
        ],
      },
      {
        id: 'buying-selling-cost-basis',
        title: 'Buying, selling & cost basis',
        summary: 'How average cost basis works, and realized vs. unrealized P&L.',
        sections: [
          {
            heading: 'Average cost basis',
            body: 'If you buy the same stock more than once at different prices, your holding tracks a single average cost basis — the weighted average of everything you paid. Buy 5 shares at $100 and 5 more at $120, and your average cost becomes $110, even though no single purchase was at that price.',
          },
          {
            heading: 'Realized vs. unrealized',
            body: "Profit and loss on shares you still own is \"unrealized\" — it's paper gains or losses that move with the current price and could vanish before you sell. The moment you sell, that gain or loss is \"realized\" — locked in for good.",
          },
          {
            heading: 'Selling and your cost basis',
            body: 'When you sell part of a position, the app compares the sale price to your average cost basis to calculate realized profit or loss on just those shares. Your remaining shares keep the same average cost basis they had before.',
          },
        ],
        quiz: [
          {
            question: "You buy 10 shares at $50, then 10 more at $70. What's your average cost basis per share?",
            options: ['$50', '$60', '$70', '$120'],
            correctIndex: 1,
            explanation: '(10×$50 + 10×$70) ÷ 20 shares = $60 average cost.',
          },
          {
            question: "When does a gain or loss become 'realized'?",
            options: ['The moment the price changes', 'Only at the end of the year', 'When you actually sell the shares', 'As soon as you buy'],
            correctIndex: 2,
            explanation: "Unrealized P&L is just on paper; it becomes realized only once you sell.",
          },
        ],
      },
    ],
  },
  {
    id: 'risk-and-diversification',
    title: 'Risk & Diversification',
    icon: '⚖️',
    lessons: [
      {
        id: 'volatility',
        title: 'Volatility',
        summary: 'How much — and how fast — a price swings, and why that matters.',
        sections: [
          {
            heading: 'What volatility means',
            body: "Volatility describes how much — and how fast — a stock's price swings up and down. A low-volatility stock might move less than 1% on a typical day; a high-volatility stock can swing 5-10% or more.",
          },
          {
            heading: "Volatility isn't automatically bad",
            body: "Higher volatility means bigger potential gains and bigger potential losses in the same breath — it's a measure of uncertainty, not of quality. A steady, low-volatility company isn't necessarily a \"better\" investment than a volatile one; they just carry different risk profiles.",
          },
          {
            heading: 'Volatility and your emotions',
            body: 'The more volatile a holding, the more your portfolio value will jump around day to day. Watching a volatile stock swing 8% in an afternoon can tempt you into reacting emotionally instead of sticking to a plan.',
          },
        ],
        quiz: [
          {
            question: "What does 'high volatility' mean for a stock?",
            options: [
              'It always goes up',
              'Its price moves are frequent and large in both directions',
              'It is guaranteed to be a bad investment',
              'It has no trading volume',
            ],
            correctIndex: 1,
            explanation: 'Volatility measures the size and speed of price swings, in either direction.',
          },
          {
            question: 'Is high volatility always a bad sign?',
            options: [
              'Yes, avoid it entirely',
              'No — it just means bigger potential swings, both up and down',
              'Yes, it means the company is failing',
              'No, it means the stock will definitely rise',
            ],
            correctIndex: 1,
            explanation: "Volatility is about the size of price swings, not a verdict on whether they'll be good or bad.",
          },
        ],
      },
      {
        id: 'diversification',
        title: 'Diversification',
        summary: "Why spreading your bets protects the rest of your portfolio.",
        sections: [
          {
            heading: "Don't put all your eggs in one basket",
            body: "Diversification means spreading your money across multiple companies, sectors, or asset types so that one company's bad quarter — or a whole industry's downturn — doesn't sink your entire portfolio.",
          },
          {
            heading: 'What concentration risk looks like',
            body: "If your entire virtual portfolio is one stock and that company reports bad news, your whole account value can drop sharply in a single day. Spread across ten unrelated companies, the same bad news from one of them barely dents your total.",
          },
          {
            heading: 'Diversification in practice',
            body: 'You don\'t need dozens of positions to diversify meaningfully — even 5-10 holdings across different industries (tech, healthcare, energy, consumer goods) meaningfully reduces the damage any single company can do. Try building a small, varied portfolio here and compare how it behaves to a single big bet.',
          },
        ],
        quiz: [
          {
            question: 'What is the main benefit of diversification?',
            options: [
              'It guarantees higher returns',
              'It reduces the impact any single investment can have on your whole portfolio',
              'It eliminates all risk completely',
              'It lets you avoid doing research',
            ],
            correctIndex: 1,
            explanation: 'Diversification spreads risk around so no single holding can sink your entire portfolio.',
          },
          {
            question: 'Which portfolio is more diversified?',
            options: [
              '100% of your cash in one company',
              'Your cash split across 8 companies in different industries',
              'Your cash split between two companies in the same industry',
              'It doesn\'t matter',
            ],
            correctIndex: 1,
            explanation: 'Spreading across multiple companies and industries reduces concentration risk the most.',
          },
        ],
      },
    ],
  },
  {
    id: 'tracking-performance',
    title: 'Tracking Performance',
    icon: '📊',
    lessons: [
      {
        id: 'profit-and-loss',
        title: 'Profit & loss',
        summary: 'The difference between unrealized, realized, and total P&L.',
        sections: [
          {
            heading: 'Two kinds of P&L',
            body: "Your dashboard splits profit and loss into two numbers. Unrealized P&L is the paper gain or loss on shares you still hold, calculated against the current market price — it moves every time the price does. Realized P&L is money you've actually locked in by selling.",
          },
          {
            heading: 'Why the distinction matters',
            body: "A large unrealized gain can shrink — or vanish — if the price falls before you sell. Only realized gains are truly \"in the bank\". Watching both numbers separately helps you understand how much of your performance is confirmed versus still at the market's mercy.",
          },
          {
            heading: 'Total P&L',
            body: "Your total P&L combines both: realized gains or losses from past sales, plus the current unrealized gain or loss on everything you're still holding. It's the single best snapshot of how you're doing overall.",
          },
        ],
        quiz: [
          {
            question: 'Which type of P&L can still change value day to day?',
            options: ['Realized P&L', 'Unrealized P&L', 'Neither, both are fixed', 'Both change at the same fixed rate'],
            correctIndex: 1,
            explanation: 'Unrealized P&L tracks your current holdings against the live price, so it moves until you sell.',
          },
          {
            question: "When is a gain 'locked in'?",
            options: [
              'As soon as the price goes up',
              'Only once you sell the shares',
              'At the end of the trading day automatically',
              'Never — gains always disappear',
            ],
            correctIndex: 1,
            explanation: 'A gain becomes realized — locked in — only when you actually sell.',
          },
        ],
      },
      {
        id: 'roi-and-leaderboard',
        title: 'ROI and the Leaderboard',
        summary: 'How return percentage makes ranking traders fair.',
        sections: [
          {
            heading: 'What ROI measures',
            body: "Return on investment (ROI) expresses your profit or loss as a percentage of what you started with, rather than a raw dollar amount. A $500 gain means very different things to a $1,000 account and a $100,000 account — ROI puts everyone on the same scale.",
          },
          {
            heading: 'How the Leaderboard uses ROI',
            body: 'The Leaderboard ranks every trader by their ROI over a chosen time window — 1 day, 1 week, 1 month, 3 months, 6 months, 1 year, or all time — instead of raw portfolio value. Because everyone starts with the same $10,000, comparing ROI is a fair way to see whose recent decisions have performed best.',
          },
          {
            heading: 'Reading different time windows',
            body: 'A trader can rank #1 on the 1-day leaderboard after a lucky short-term swing, while ranking lower on the all-time board once that swing is measured against their whole history. Longer windows tend to reward consistent decision-making over lucky timing.',
          },
        ],
        quiz: [
          {
            question: 'Why does the Leaderboard rank by ROI percentage instead of total dollar value?',
            options: [
              'Dollar value is easier to calculate',
              'Because everyone starts with the same cash, ROI is a fairer comparison of trading performance',
              'ROI is always a bigger number',
              "It doesn't — it ranks by dollar value",
            ],
            correctIndex: 1,
            explanation: 'Since every account starts at the same $10,000, ranking by ROI% compares decisions, not starting capital.',
          },
          {
            question: 'What might explain a trader ranking #1 on the 1-day board but much lower on the all-time board?',
            options: [
              'A data error',
              "A short-term lucky swing that isn't representative of their longer track record",
              'The leaderboard is randomized',
              'All-time and 1-day always show the same order',
            ],
            correctIndex: 1,
            explanation: 'Short windows can be swayed by a single lucky (or unlucky) move; longer windows smooth that out.',
          },
        ],
      },
    ],
  },
  {
    id: 'investing-mindset',
    title: 'Investing Mindset',
    icon: '🧠',
    lessons: [
      {
        id: 'long-term-thinking',
        title: 'Long-term thinking',
        summary: 'Time in the market vs. timing the market.',
        sections: [
          {
            heading: 'Time in the market vs. timing the market',
            body: "Trying to buy right before a rally and sell right before a drop — \"timing the market\" — is notoriously difficult, even for professionals. A more reliable pattern historically has been simply staying invested over long periods, riding out the dips along the way.",
          },
          {
            heading: 'The cost of overtrading',
            body: "Frequent buying and selling doesn't just add real-world costs (fees, taxes) — it also multiplies the number of decisions you can get wrong. Each trade is a fresh bet on short-term direction, which is far harder to call correctly than long-term company performance.",
          },
          {
            heading: 'Using this simulator to practice patience',
            body: 'Because there\'s no real money at risk, it\'s easy to fall into rapid-fire trading just to see what happens. Try the opposite: pick a few companies you believe in, hold them, and check back over weeks instead of minutes. Compare how that feels — and performs — against more frequent trading.',
          },
        ],
        quiz: [
          {
            question: "What does 'time in the market vs. timing the market' refer to?",
            options: [
              'Trading only at night',
              'Staying invested over the long run instead of trying to predict short-term highs and lows',
              'Only trading when the market is closed',
              'Checking prices every minute',
            ],
            correctIndex: 1,
            explanation: 'It contrasts patient, long-term holding with attempts to precisely predict short-term price swings.',
          },
          {
            question: "What's one downside of frequent trading?",
            options: [
              'It guarantees losses',
              'Each trade is another short-term bet that can go wrong, and real trading adds costs like fees and taxes',
              'It is illegal',
              'It has no downsides',
            ],
            correctIndex: 1,
            explanation: 'More trades mean more chances to be wrong about short-term direction, plus real-world costs in a live account.',
          },
        ],
      },
      {
        id: 'common-beginner-mistakes',
        title: 'Common beginner mistakes',
        summary: 'Hype-chasing, concentration, and emotional decisions.',
        sections: [
          {
            heading: 'Chasing hype',
            body: "Buying a stock purely because it's trending or \"everyone's talking about it\" means buying after the price has often already risen a lot — and hype fades faster than it builds. Ask what you know about the company, not just what you've heard about the stock.",
          },
          {
            heading: 'Putting everything into one bet',
            body: "It's tempting to go all-in on your highest-conviction idea, but even great companies have bad quarters. Spreading risk across multiple holdings protects you from being wrong about any single company.",
          },
          {
            heading: 'Letting emotions drive decisions',
            body: 'Panic-selling during a dip and euphoria-buying during a rally are two sides of the same trap: reacting to price movement instead of to any actual change in the company. A brief pause before reacting to a big price swing is one of the simplest habits that separates disciplined investors from impulsive ones.',
          },
          {
            heading: 'Ignoring fees and taxes (in the real world)',
            body: "This simulator doesn't charge fees, but real trading does — every trade can carry transaction costs, and in many places selling at a profit triggers taxes. Frequent trading in a real account quietly erodes returns in a way that's easy to overlook.",
          },
        ],
        quiz: [
          {
            question: "What's a risk of buying a stock 'because everyone's talking about it'?",
            options: [
              'There is no risk',
              "You may be buying after the price has already risen on hype that's about to fade",
              'Hype always predicts long-term success',
              'It guarantees a diversified portfolio',
            ],
            correctIndex: 1,
            explanation: "Hype-driven buying often means paying a price that already reflects the excitement — with little room left to gain.",
          },
          {
            question: "What's a healthier response to a sudden, sharp price drop in a stock you hold?",
            options: [
              'Sell immediately without checking anything else',
              'Buy more immediately no matter what',
              'Pause, and consider whether anything about the company actually changed before reacting',
              'Panic',
            ],
            correctIndex: 2,
            explanation: 'Reacting to the price alone — instead of what actually changed about the business — is a common emotional trap.',
          },
        ],
      },
    ],
  },
];
